/**
 * Name: UUID_Entity.java
 * Authors: Anzac Morel
 * Date: 19/08/2019
 */

package seng202.teamsix.managers;

//import seng202.teamsix.data.Order;

//import java.util.ArrayList;

public class FinancialManager {
    //private ArrayList<Order> order_list;
    //int totalProfit = 0;

    /**
     * Constructor for the HistoricalManager class, used if there is no current list of orders
     */
    //public FinancialManager() {
        //order_list = new ArrayList<>();
    //}

    /**
     * Adds the given Order to the ArrayList of orders
     * @param order Order to be added to the list of orders
     */
    //public void addOrder(Order order) {
        //if (!order_list.contains(order)) {
            //order_list.add(order);
       // } else {
            //System.err.println("Can't add same order to the list of orders!");
        //}
    //}

    /**
     * Prints the price payed by the customer for the order and calls generateProfit
     */
    //public void printTotalCostOfOrder() {
        //int total = 0;
        //for (int index = 0; index < order_list.size(); index++) {
            //total += order_list.get(index).getPrice();
        //}
        //generateProfit(total);
        //System.out.println(total);
    //}

    /**
     * Calculates the money gained from the order less the cost for the food truck to create the order (ingredients etc)
     * @param income total price payed by the customer (generated by the printTotalCostOfOrder function)
     */
    //public void generateProfit(int income) {
        //for (int index = 0; index < order_list.size(); index++) {
            //income -= order_list.get(index).getCost();
        //}
       // System.out.println(income);
    //}

    /**
     * Sets the new value for total profit
     * @param order Order to be added to the list of orders
     */
    //public void setTotalProfit(int newProfit) {
        //totalProfit = newProfit;
    //}

    /**
     * Returns the current value of total profit
     * @return totalProfit
     */
   // public int getTotalProfit() {
        //return totalProfit;
    //}
}
